### PR TITLE
Multi-cluster Energy/Barycenter Check Code

### PR DESCRIPTION
**Pull request by BigBang0072**

### CODE REVIEW

**Comment by BigBang0072** [comment]
I have to find and fix the bug for layers beyond 28.

**Comment by BigBang0072** [comment]
I have to find and fix the bug for layers beyond 28.

**Comment by BigBang0072** [comment]
Merge Conflict Resolved. Ready to be pulled and run.

**Comment by BigBang0072** [comment]
I have added the Multiprocessing of Interpolation Coefficient calculation on the different layers.
Now it will fasten up by reducing time at least twice as before.

Ready to pull.

**Comment by BigBang0072** [comment]
The image creation function tested and added.
The changes could be merged now.

**Comment by grasseau** [comment]
Ok Abhinav done, thanks

**Pull request merged**
